print("Problema 1")
print("Struguri  100 kg")
print("Mere  10 tone")
print("Cartofi  250 kg")
print("Varza  1000 q")

print("Problema 2")
a=3
b=4
print("a=3")
print("b=4") 
print("a+b=" , a+b)
print("a-b=" , a-b)
print("a*b=" , a*b)
print("a/b=" , a/b)
print("b/a=" , b/a)
print("Citul din a/b=" , a//b)
print("Citul din b/a=" , b//a)
print("Restul din a/b=" , a%b)
print("Restul din b/a=", b%a)
print("a**b=" , a**b)
print("b**a=" , b**a)
print("Problema 3")
L=int(input("Lungimea muchiei cubului= "))
print("volumul=", 4*L, "cm")
print("perimetrul=", L**3, "cm3")
print("aria tuturor suprafetelor=", 6*(L**2), "cm2")
print("Problema 4")
n=int(input("numar natural="))
print(n, "metri in centimetri", n*100)
print(n, "kilograme in miligrame", n*10000)
print("In", n, "ani", n*52, "saptamini", n*365, "zile", n*12, "luni")
print("Problema 5")
x=True
y=False
print(x and y)
print(y and x)
print(x or y)
print(y or x)
print(not x)
print(not y)
